## Check-in 1

1. The integer number -999 is often used to represent missing values. Create a `pandas.Series` named `s` with four integer values, two of which are -999. The index of this series should be the the letters A through D.

2. In the [`pandas.Series` documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.html), look for the method `mask()`. Use this method to update the series `s` so that the -999 values are replaced by NA values. HINT: check the first example in the method's documentation.


## Check-in 2

We can access the data frame's column names via the [`columns` attribute](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html#pandas.DataFrame.columns). Update the column names to C1 and C2 by updating this attribute.

In [8]:
import pandas as pd
import numpy as np

In [32]:
s = pd.Series([6, 7, -999, -999], index = ['A', 'B', 'C', 'D'])
s

A      6
B      7
C   -999
D   -999
dtype: int64

In [34]:
s.mask(s<0)

A    6.0
B    7.0
C    NaN
D    NaN
dtype: float64

In [36]:
type(np.nan)

float

In [6]:
s = s.mask(s == -999)
s

A    6.0
B    7.0
C    NaN
D    NaN
dtype: float64

In [37]:
d = {'col_name_1' : pd.Series(np.arange(3)),
    'col_name_2' : pd.Series([3.1, 3.2, 3.3])}
d

{'col_name_1': 0    0
 1    1
 2    2
 dtype: int64,
 'col_name_2': 0    3.1
 1    3.2
 2    3.3
 dtype: float64}

In [38]:
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [39]:
df.columns = ['C1', 'C2']
df

   C1   C2
0   0  3.1
1   1  3.2
2   2  3.3

In [40]:
df.index = [1,2,3]
df

   C1   C2
1   0  3.1
2   1  3.2
3   2  3.3

In [41]:
df.index = ['1','2','3']
df

   C1   C2
1   0  3.1
2   1  3.2
3   2  3.3